services:
  # Backend Service
  - type: web
    name: inventory-backend
    plan: free
    runtime: docker
    sourceDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-database
          property: connectionString

  # Frontend Service
  - type: web
    name: inventory-frontend
    plan: free
    runtime: static
    sourceDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production

databases:
  # PostgreSQL Database
  - name: inventory-database
    plan: free 